In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
features = pd.read_csv('../Datasets/uci_har/features.txt',header=None,sep=' ',names=('ID','Activity'))
labels = pd.read_csv('../Datasets/uci_har/activity_labels.txt',header=None,sep=' ',names=('ID','Sensor'))

X_train = pd.read_table('../Datasets/uci_har/train/X_train.txt',header=None,sep='\s+')
y_train = pd.read_table('../Datasets/uci_har/train/y_train.txt',header=None,sep='\s+')

X_test = pd.read_table('../Datasets/uci_har/test/X_test.txt',header=None,sep='\s+')
y_test = pd.read_table('../Datasets/uci_har/test/y_test.txt',header=None,sep='\s+')

train_sub = pd.read_table('../Datasets/uci_har/train/subject_train.txt',header=None,names=['SubjectID'])
test_sub = pd.read_table('../Datasets/uci_har/test/subject_test.txt',header=None,names=['SubjectID'])

In [3]:
X_train.head()

0         1         2         3         4         5         6    \
0  0.288585 -0.020294 -0.132905 -0.995279 -0.983111 -0.913526 -0.995112   
1  0.278419 -0.016411 -0.123520 -0.998245 -0.975300 -0.960322 -0.998807   
2  0.279653 -0.019467 -0.113462 -0.995380 -0.967187 -0.978944 -0.996520   
3  0.279174 -0.026201 -0.123283 -0.996091 -0.983403 -0.990675 -0.997099   
4  0.276629 -0.016570 -0.115362 -0.998139 -0.980817 -0.990482 -0.998321   

        7         8         9      ...          551       552       553  \
0 -0.983185 -0.923527 -0.934724    ...    -0.074323 -0.298676 -0.710304   
1 -0.974914 -0.957686 -0.943068    ...     0.158075 -0.595051 -0.861499   
2 -0.963668 -0.977469 -0.938692    ...     0.414503 -0.390748 -0.760104   
3 -0.982750 -0.989302 -0.938692    ...     0.404573 -0.117290 -0.482845   
4 -0.979672 -0.990441 -0.942469    ...     0.087753 -0.351471 -0.699205   

        554       555       556       557       558       559       560  
0 -0.112754  0.030400 -0.464761 -0.018446 -0.841247  0.179941 -0.058627  
1  0.053477 -0.007435 -0.732626  0.703511 -0.844788  0.180289 -0.054317  
2 -0.118559  0.177899  0.100699  0.808529 -0.848933  0.180637 -0.049118  
3 -0.036788 -0.012892  0.640011 -0.485366 -0.848649  0.181935 -0.047663  
4  0.123320  0.122542  0.693578 -0.615971 -0.847865  0.185151 -0.043892  

[5 rows x 561 columns]

In [4]:
X_train.columns = features.iloc[:,1]
X_test.columns = features.iloc[:,1]

In [5]:
y_train.columns = ['Activity']
y_test.columns = ['Activity']

In [6]:
X_train['SubjectID'] = train_sub
X_test['SubjectID'] = test_sub

In [7]:
X_train.head()

Activity  tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0                  0.288585          -0.020294          -0.132905   
1                  0.278419          -0.016411          -0.123520   
2                  0.279653          -0.019467          -0.113462   
3                  0.279174          -0.026201          -0.123283   
4                  0.276629          -0.016570          -0.115362   

Activity  tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  \
0                -0.995279         -0.983111         -0.913526   
1                -0.998245         -0.975300         -0.960322   
2                -0.995380         -0.967187         -0.978944   
3                -0.996091         -0.983403         -0.990675   
4                -0.998139         -0.980817         -0.990482   

Activity  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  \
0                -0.995112         -0.983185         -0.923527   
1                -0.998807         -0.974914         -0.957686   
2                -0.996520         -0.963668         -0.977469   
3                -0.997099         -0.982750         -0.989302   
4                -0.998321         -0.979672         -0.990441   

Activity  tBodyAcc-max()-X    ...      fBodyBodyGyroJerkMag-skewness()  \
0                -0.934724    ...                            -0.298676   
1                -0.943068    ...                            -0.595051   
2                -0.938692    ...                            -0.390748   
3                -0.938692    ...                            -0.117290   
4                -0.942469    ...                            -0.351471   

Activity  fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
0                               -0.710304                    -0.112754   
1                               -0.861499                     0.053477   
2                               -0.760104                    -0.118559   
3                               -0.482845                    -0.036788   
4                               -0.699205                     0.123320   

Activity  angle(tBodyAccJerkMean),gravityMean)  \
0                                     0.030400   
1                                    -0.007435   
2                                     0.177899   
3                                    -0.012892   
4                                     0.122542   

Activity  angle(tBodyGyroMean,gravityMean)  \
0                                -0.464761   
1                                -0.732626   
2                                 0.100699   
3                                 0.640011   
4                                 0.693578   

Activity  angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  \
0                                    -0.018446             -0.841247   
1                                     0.703511             -0.844788   
2                                     0.808529             -0.848933   
3                                    -0.485366             -0.848649   
4                                    -0.615971             -0.847865   

Activity  angle(Y,gravityMean)  angle(Z,gravityMean)  SubjectID  
0                     0.179941             -0.058627          1  
1                     0.180289             -0.054317          1  
2                     0.180637             -0.049118          1  
3                     0.181935             -0.047663          1  
4                     0.185151             -0.043892          1  

[5 rows x 562 columns]

In [8]:
y_train.head()

Activity
0         5
1         5
2         5
3         5
4         5

In [9]:
X_train.isnull().sum().max()

0

In [10]:
X_test.isnull().sum().max()

0

In [11]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import classification_report,confusion_matrix,mean_squared_error

In [12]:
from sklearn.model_selection import KFold,StratifiedKFold 

In [13]:
from sklearn.model_selection import RepeatedKFold

In [14]:
def rmsle(y, y_pred):
    return np.sqrt(mean_squared_error(y, y_pred))

In [15]:
dtree = DecisionTreeClassifier()

In [16]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [17]:
y_pred = dtree.predict(X_test)

In [18]:
print(rmsle(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.415185127615883
[[457  20  19   0   0   0]
 [ 67 353  51   0   0   0]
 [ 15  45 360   0   0   0]
 [  0   0   0 372 119   0]
 [  0   0   0  70 462   0]
 [  0   0   0   0   0 537]]
             precision    recall  f1-score   support

          1       0.85      0.92      0.88       496
          2       0.84      0.75      0.79       471
          3       0.84      0.86      0.85       420
          4       0.84      0.76      0.80       491
          5       0.80      0.87      0.83       532
          6       1.00      1.00      1.00       537

avg / total       0.86      0.86      0.86      2947



In [19]:
random_forest = RandomForestClassifier(n_estimators=6)

In [20]:
kfold = KFold().split(X_train,y_train)

In [21]:
for k, train in enumerate(kfold):
    random_forest.fit(X_train[train], y_train[train])

TypeError: unhashable type: 'numpy.ndarray'

In [112]:
X_train.head()

Activity  tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0                  0.288585          -0.020294          -0.132905   
1                  0.278419          -0.016411          -0.123520   
2                  0.279653          -0.019467          -0.113462   
3                  0.279174          -0.026201          -0.123283   
4                  0.276629          -0.016570          -0.115362   

Activity  tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  \
0                -0.995279         -0.983111         -0.913526   
1                -0.998245         -0.975300         -0.960322   
2                -0.995380         -0.967187         -0.978944   
3                -0.996091         -0.983403         -0.990675   
4                -0.998139         -0.980817         -0.990482   

Activity  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  \
0                -0.995112         -0.983185         -0.923527   
1                -0.998807         -0.974914         -0.957686   
2                -0.996520         -0.963668         -0.977469   
3                -0.997099         -0.982750         -0.989302   
4                -0.998321         -0.979672         -0.990441   

Activity  tBodyAcc-max()-X    ...      fBodyBodyGyroJerkMag-skewness()  \
0                -0.934724    ...                            -0.298676   
1                -0.943068    ...                            -0.595051   
2                -0.938692    ...                            -0.390748   
3                -0.938692    ...                            -0.117290   
4                -0.942469    ...                            -0.351471   

Activity  fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
0                               -0.710304                    -0.112754   
1                               -0.861499                     0.053477   
2                               -0.760104                    -0.118559   
3                               -0.482845                    -0.036788   
4                               -0.699205                     0.123320   

Activity  angle(tBodyAccJerkMean),gravityMean)  \
0                                     0.030400   
1                                    -0.007435   
2                                     0.177899   
3                                    -0.012892   
4                                     0.122542   

Activity  angle(tBodyGyroMean,gravityMean)  \
0                                -0.464761   
1                                -0.732626   
2                                 0.100699   
3                                 0.640011   
4                                 0.693578   

Activity  angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  \
0                                    -0.018446             -0.841247   
1                                     0.703511             -0.844788   
2                                     0.808529             -0.848933   
3                                    -0.485366             -0.848649   
4                                    -0.615971             -0.847865   

Activity  angle(Y,gravityMean)  angle(Z,gravityMean)  SubjectID  
0                     0.179941             -0.058627          1  
1                     0.180289             -0.054317          1  
2                     0.180637             -0.049118          1  
3                     0.181935             -0.047663          1  
4                     0.185151             -0.043892          1  

[5 rows x 562 columns]

In [129]:
#Rp_Kfold = RepeatedKFold(n_splits=5).split(X_train,y_train)

#for k, train in enumerate(Rp_Kfold):
#    random_forest.fit(X_train[train],y_train[train])

In [130]:
#St_Kfold = StratifiedKFold(n_splits=5).split(X_train,y_train)

#for k, train in enumerate(St_Kfold):
#    random_forest.fit(X_train[train],y_train[train])

In [57]:
random_forest.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=6, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [74]:
y_pred = random_forest.predict(X_test)

In [59]:
print(rmsle(y_test,y_pred))
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))

0.40734684940193044
[[467  75  33   0   0   0]
 [ 20 384  58   0   0   0]
 [  9  12 329   0   0   0]
 [  0   0   0 438  94   0]
 [  0   0   0  50 438   0]
 [  0   0   0   3   0 537]]
             precision    recall  f1-score   support

          1       0.94      0.81      0.87       575
          2       0.82      0.83      0.82       462
          3       0.78      0.94      0.85       350
          4       0.89      0.82      0.86       532
          5       0.82      0.90      0.86       488
          6       1.00      0.99      1.00       540

avg / total       0.89      0.88      0.88      2947



In [75]:
print('Using KFold cross validation technique')
print(rmsle(y_test,y_pred))
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))

Using KFold cross validation technique
0.3833132927785924
[[477  53  33   0   0   0]
 [  2 409  48   0   0   0]
 [ 17   9 339   0   0   0]
 [  0   0   0 453  81   0]
 [  0   0   0  38 450   1]
 [  0   0   0   0   1 536]]
             precision    recall  f1-score   support

          1       0.96      0.85      0.90       563
          2       0.87      0.89      0.88       459
          3       0.81      0.93      0.86       365
          4       0.92      0.85      0.88       534
          5       0.85      0.92      0.88       489
          6       1.00      1.00      1.00       537

avg / total       0.91      0.90      0.90      2947



In [44]:
gra_boost = GradientBoostingClassifier()

In [45]:
gra_boost.fit(X_train,y_train)
pred = gra_boost.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [46]:
print(rmsle(y_test,pred))
print(confusion_matrix(pred,y_test))
print(classification_report(pred,y_test))

0.2750821205701062
[[487  24   7   0   0   0]
 [  6 439  27   2   0   0]
 [  3   7 385   0   0   0]
 [  0   1   0 417  31   0]
 [  0   0   1  72 501   0]
 [  0   0   0   0   0 537]]
             precision    recall  f1-score   support

          1       0.98      0.94      0.96       518
          2       0.93      0.93      0.93       474
          3       0.92      0.97      0.94       395
          4       0.85      0.93      0.89       449
          5       0.94      0.87      0.91       574
          6       1.00      1.00      1.00       537

avg / total       0.94      0.94      0.94      2947

